### ISSUE TITLE
.gitignore with npm default configuration is missing

### ISSUE THREAD

**Issue by tiagocmendes** [gmatosferreira/asharedprojectforei#1]
A .gitignore file must be present on the project root with a configuration like this: [https://github.com/github/gitignore/blob/master/Node.gitignore](https://github.com/github/gitignore/blob/master/Node.gitignore)

**Comment by gmatosferreira** [comment]
I forgot to put it at the public repo. Thanks for noticing! 😉

**Comment by tiagocmendes** [comment]
No problem 😉
