### ISSUE TITLE
Can´t run the project locally due to missing folder

### ISSUE THREAD

**Issue by tiagocmendes** [gmatosferreira/asharedprojectforei#2]
The folder **Components/Data** is missing in project repo, giving the following error when trying to run locally: 

![imagem](https://user-images.githubusercontent.com/31295384/99957052-fab18800-2d7e-11eb-894f-3355443ad558.png)

**Comment by gmatosferreira** [comment]
That problem is explained on [README](https://github.com/gmatosferreira/asharedprojectforei/blob/main/README.md).

> When you try execute this command it will throw a compilation error because the project is relying on the folders `src/Data` and `public/images` to get the data and images for rendering, that do not exist. We are generating sample data for this purpose and will make it available soon. Until then, feel free to explore the code!

I'll make them available in the next few days.

**Comment by gmatosferreira** [comment]
That problem is explained on [README](https://github.com/gmatosferreira/asharedprojectforei/blob/main/README.md).

> When you try execute this command it will throw a compilation error because the project is relying on the folders `src/Data` and `public/images` to get the data and images for rendering, that do not exist. We are generating sample data for this purpose and will make it available soon. Until then, feel free to explore the code!

I'll make them available in the next few days.

**Comment by gmatosferreira** [comment]
I've just added the files that were missing. You should be able to compile the project now! 🙂
