### ISSUE TITLE
Missing peer dependencies of typescript and jquery@>=1.8.0

### ISSUE THREAD

**Issue by tiagocmendes** [gmatosferreira/asharedprojectforei#3]
Just run the following commands on project root:

```console
$ npm install typescript --save
$ npm install jquery@>=1.8.0 --save
```

**Warning message:** 

![imagem](https://user-images.githubusercontent.com/31295384/99957273-55e37a80-2d7f-11eb-85c2-81f5100aca44.png)

**Comment by gmatosferreira** [comment]
Thanks for warning. 🙂 Just fixed it!
